### PR TITLE
Bumped devDependencies

### PR DESCRIPTION
**Pull request by nponeccop**
babel to 7.x
jest to 26.x
typescript to 4.x

### CODE REVIEW

**Comment by nponeccop** [comment]
Note that Travis fails on anything earlier than Node 10 because Jest 26 doesn't support it.

So we should decide whether we drop old nodes. If we don't - we need to change the CI scripts to install the appropriate Jest major version for node 6 and node 8.

If  we drop, then we need to increment the major version of `jest-mock-console` to 2

**Comment by bpedersen** [comment]
Let's bump the minor version of this to move to jest@26 and leave off earlier node versions in travis. We'll look into this further if we get reports that this causes pain for people.

**Comment by nponeccop** [comment]
This way?

**Comment by bpedersen** [comment]
Looks good

**Pull request merged**
